### PR TITLE
fix #211 - wait url can contain user information

### LINKED ISSUE #211: Start wait url does not support user information in URL
Currently _wait_ option times out always when you try to refer to protected URL.
Specifying  user auth info in URL does not make any difference.

I added some logging to HttpPingChecker and reason is http error 401:
```
...
[DEBUG] DOCKER> wait url 'http://user:pass@host/someurl' exception: Read timed out
[DEBUG] DOCKER> wait url 'http://user:pass@host/someurl' response code: 401
...
```

*WaitUtil.HttpPingChecker* uses *java.net.HttpURLConnection* and this is probable reason.

I think there are two options to allow user auth info:
* use apache HttpClient lib which support user info by default (library is already in plugin depedencies).
* keep using *java.net.HttpURLConnection* but:
  * extend configuration with authorization user / password (required configuration format change), or
  * extract auth info from specified url before using it.

I tested HttpClient option and can supply pull request for that.

### PR DESCRIPTION
**Pull request by tdomzal**
Replace ping implementation from java.net.HttpURLConnection
to Apache HttpClient. Generate ping errors diagnostics info
when maven debug level is active.
Fixes #211.

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks a lot ! Could you please sign-off your PR as described [here](https://github.com/rhuss/docker-maven-plugin/blob/master/doc/contributing.md) ? 

I will integrate it for 0.13.2 which will be released probably end of next week.

**Comment by tdomzal** [comment]
Sure. 
Take a look at updated commit message if it is OK.

**Comment by rhuss** [comment]
perfect, thanks !

**Comment by rhuss** [comment]
Merged into branch integration. 'hope you don't mind that I removed the debugging again (in order to keep the API a bit cleaner). 

If there's a good reason we can add it again.

Thanks !

**Comment by tdomzal** [comment]
I thought logging may be handy when visible with maven -X flag but of course I don't mind if you just clean it out.
Thanks!

**Pull request closed without merging**
