### PR TITLE
If the StartMojo fails, stop all started containers

### PR DESCRIPTION
**Pull request by stevenschlansker**
We're about to fail the build anyway, so let's not leave heavyweight resources lying around.  ( HubSpot/Singularity#607 )

### CODE REVIEW

**Comment by tpetr** [comment]
:+1:

**Comment by stevenschlansker** [comment]
@jgangemi Sure why not :smile:

**Comment by stevenschlansker** [comment]
I'm sad that this didn't make 0.13.1, maybe we could get a 0.13.2?

**Comment by rhuss** [comment]
Sorry, I had to get out 0.13.1 very quickly because of a nasty behaviour of the special version of Docker Fedora/Centos uses and 'docker:push'. 0.13.1 adds a workaround.

I highly appreciate you contribution and 0.13.2 will follow next week. Please don't be disappointed, typically it takes a bit (one to four weeks) until a PR is integrated. 

Thanks a lot ...

**Comment by rhuss** [comment]
@stevenschlansker, in the meantime could you do me a favour an sign-off the PR ? How this is done is explained [here](https://github.com/rhuss/docker-maven-plugin/blob/master/doc/contributing.md)

And if you want to go fancy, you could also rebase it to be a single commit (git rebase -i). But that's not so important.

**Comment by stevenschlansker** [comment]
No worries.  I added the sign-off.  I think squishing the commits does not make sense, as they are truly unrelated fixups, so they should be two separate commits.

Looking forward to 0.13.2 :+1:

**Comment by rhuss** [comment]
Intgerated it into branch 'integration', will be part of 0.13.2 end of this week.

Thanks again !

**Pull request closed without merging**
