### PR TITLE
allow linking / volumesFrom external containers

### LINKED ISSUE #195: allow linking to containers not managed by the plugin
i thought i had seen an issue regarding this before, but perhaps it was for referencing volumes from other containers.

in any case, when starting a container via the plugin, i'd like to be able to link to an existing container that has been started via some other mechanism.

in an effort not to break existing configuration, my thought is to just add a new xml block to the run section:
```xml
<linkExternal>
  <link>container_name:env_var_prefix</link>
</linkExternal>
```
thoughts? i'm open to different element names, etc.

### PR DESCRIPTION
**Pull request by jgangemi**
resolves #195 and #73 

- pulled fine grained query methods out of DockerAccess into QueryService
- added coarse grained list/inspect methods to DockerAccess
- introduced model objects
- refactored RunService to accept DocerAccess instance via 'initialize' method
- allow linking/mounting from external containers

Signed-off-by: Jae Gangemi <jgangemi@gmail.com>

### CODE REVIEW

**Comment by jgangemi** [comment]
ideally the `UrlBuilder` would be updated to return `DockerUrl`s for everything, but baby steps :)

**Comment by rhuss** [comment]
Thanks a lot, will have a review soon.

**Comment by jgangemi** [comment]
cool - i had a better idea on how to deal w/ the state/services this morning.

**Comment by rhuss** [comment]
Thanks, Jae ! 

Quite some changes, need a bit to walk through it ;-)

**Comment by jgangemi** [comment]
haha - don't you always when i submit something? :)

**Comment by rhuss** [comment]
Yeah, always gate keeping ;-)

**Comment by rhuss** [comment]
I worked mostly through it and cleaned up a bit (you know what that means ;-P)

I like the refactoring in the QueryService and the ServiceFactory (which I now call ServiceHub since all services are created upfront). Thanks !

Also, you know that I didn't want to introduce a fancy 'model' in order to avoid bloat. However using a model more or less as a 'proxy' to the JSON object (without copying things over) looks fine. Also, it hides a bit the inconsistence model that Docker uses in their Remote API. I introduced a `Container` interface which can be nicely implemented by both the elements returned by 'container list' and 'container inspection'. What I also did, though, I removed everything currently not needed. We can introduce this always later on.

I didn't test the functionality yet, but I think there were some gotchas (see my commit comment). Also, you looked up the name in the link config as a container name.

I pushes my changes to `195-external-linking` so it might be good idea to check this out.

**Comment by rhuss** [comment]
Hmm, just saw that 'Names' is really a part of an list element when listing containers. But it is nowhere documented and also, why it is a list ? AFAIK a container can have only one name, or ?

Strange, strange ...

**Comment by rhuss** [comment]
I asked here https://github.com/docker/docker/issues/14675

**Comment by jgangemi** [comment]
the `Names` field is undocumented at the moment but i posted an issue in the docker project and was told that when a container gets linked, it gets an additional name, eg: `['/database', '/database/application-linked-to-it'` (i may have the linkee-linker backwards, but you get the idea.

i also switched everything over to using container name instead of container id b/c that's how the cli works and if you inspect a container created that way, it shows the name and not the container id. everything worked for me when i pushed, so i'll pull down the new branch and try it out.

did you strip out all of the fields from the original `Container` object? i added all of them to pave a little way to adding a `docker:ps` mojo as those are fields that would get displayed.

**Comment by rhuss** [comment]
@jgangemi ah, thanks for the explanation. I understand now. I just pushed to the branch (with some rebasing, so please pull it a fresh). For me it works, too (after i inserted back your stuff ;-)

Yes, I stripped off on the container stuff since I didn't see any use up to now (I do this always when I see unused code ;-). Sorry. I like that you don't copy over data but convert it 'on-the-fly' making the model more  a proxy than a data object.

Also, since the container elements were quite similar for 'list' and 'inspect' I tried to unify them behind an interface. This might cease to work when you add more from the 'inspect' side. One could then either decided to throw UnsuporrtedOperationExceptions or, maybe better, extend a `ContainerDetails` on top of `Container`. What do you think ?

**Comment by jgangemi** [comment]
lol - i was originally going to call `DependencyTracker` `ContainerTracker`

**Comment by jgangemi** [comment]
everything looks good to me.

i initially thought about trying to make `Container` and `ContainerDetails` share some kind of commonality (either via an interface or one inheriting from the other) but after peeking at some other clients that exist and not seeing that done, i went the two different classes route.

glad you like the model as a proxy. i know you wanted to shy away from that but it seemed cleaner.

once you get this merged i'm gonna deal w/ #207.

**Comment by rhuss** [comment]
I will cut a release 0.13.2 tomorrow containing this fix and merge everything to master for that

thanks ...

**Pull request closed without merging**
