### PR TITLE
#181: Fix bug when authenticating to private registry

### PR DESCRIPTION
**Pull request by jdavisonc**
#181 

Fix bug when authenticating to private registry, add "serveraddress" to authentication header.

Base on the following documentation, "serveraddress" is required by Docker for authenticate. Not adding this part on header generates "Authentication required." error.

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks !

'will review this PR ASAP.

**Comment by rhuss** [comment]
Could you please sign-off the the PR as described in [here](https://github.com/rhuss/docker-maven-plugin/blob/master/doc/contributing.md) ? Thanks a lot !

**Comment by jdavisonc** [comment]
Done! If you require any further information, let me know.

**Comment by rhuss** [comment]
Thanks ;-)

I just tried out the patch and it prevented me to push to `index.docker.io` (which still works with 0.13.2) with an `Authentication failed`. I still didn't dive into this PR yet (sorry), but will check this of course.

Does pushing to `docker.io` works for you ?

**Comment by jdavisonc** [comment]
I only test the pull/push against a private repository V1, not the docker.io ones. Maybe is a error with that version only.

**Comment by rhuss** [comment]
Did you have a chance to check it with the official repository ? 

I wil postpone this PR for a later release since I'm going to cut 0.13.3 today.

**Comment by rhuss** [comment]
Is authentication still an issue for you ?

Sorry for the long delay. It seems thaat  `serveraddress` is really required for registry API V1 but not for V2 anymore. It is also somewhat redundant since the registry address is already part of the pull/push. V1 also doesn't seem to be much in use anymore, so if it is not absolutely necessary I would like drop support for this and close this PR.

Authentication will be generally be polished via #147.

**Comment by jdavisonc** [comment]
I still using V1, but anyway I resolve the problem with other solution. Thanks anyway, I'll close this PR.

**Pull request closed without merging**
