### PR TITLE
Add logic to specify exec commands during postStart and preStop

### PR DESCRIPTION
**Pull request by DennisDenuto**
PR for #266
e.g. 
```
<wait>
  <http>
    <url>http://localhost:${host.port}</url>
    <method>GET</method>
    <status>200..399</status>
  </http>
  <time>10000</time>
  <shutdown>500</shutdown>
  <exec>
    <postStart>/opt/init_db.sh<postStart>
    <preStop>/opt/notify_end.sh</preStop>
  </exec>
</wait>
```

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks for the PR, I just did a quick review. Looks real good overall. Some minor remarks:

* Could you please add some documentation to manual.md (with example) and to changelog.md ?
* /wr to the possible options when attaching to a running container: I never would expect that a tty would be set for a maven build, so I would remove `Tty` all together. Also I always would expect to attach to StdErr and StdOut and currently its also not possible to set it from the configuration. So I would remove that, too, and then maybe the whole `ExecContainerConfiguration` since all what is left is the command. We could make it a `org.jolokia.docker.maven.config.Arguments` as it is for the other shell-command related config options, too (though I don't know by heart whether there are also two forms (exec/shell) for calling the exec container.
* I would remove `Optional` in ShutdownAction because this can be realized easily with a null-check, too and wouldn't introduce a new dependency.

A general principle I try to follow is to implement only what is needed (and don't fall in the trap *we might it need it sometime* as I did top often and frankly nearly never happened) and even when I think things like `Optional` are a good thing, I want to introduce that only when there is a good reason weighting out the costs of an extra dependency. From my feeling this is not yet the case yet.

**Comment by DennisDenuto** [comment]
Thanks for the feedback!
From what I can see the /exec endpoint only accepts 'exec' not 'shell'. (Not sure if that changes your opinion on whether Arguments should still be used since it maintains both shell and exec.)

wrt Optional, I figured it was ok to use since guava was on the classpath and was only a private helper method. But I agree looking back now it looks out of place considering null checks are mainly used. :-)

**Comment by DennisDenuto** [comment]
Hey Rhuss,
were you able to check the changes made to this PR? (following your feedback).

**Comment by rhuss** [comment]
Ooops, didn't get any update by GitHub that the PR was changed. Will have a look ASAP.

**Comment by rhuss** [comment]
Thanks again ! I'm going to cleanup the duplicate code in `ShutdownAction` and `RunService`, too, since there is now some overlap here.

**Comment by DennisDenuto** [comment]
Cool Thanks heaps Rhuss

**Comment by robzet** [comment]
Can I use this to run more than one command? I cant seam to get it working. I have tried with two commands separated by ; or && (as &amp;&amp;). Only one command is ran.I can see both commands getting sent over rest interface as a "Cmd": "[]" but I get errors related to it and it does not look like its interpreted as two commands correctly. Any ideas?

As i believe the first answer will be "put the commands in a script and execute that in one command" I want to also add some background to the problem. My setup runs well on Linux, but not on Windows. The command is supposed to run a script file with several commands in. On Windows this file looses its permissions somehow during transfer to the docker container and this is why I need to run two commands. One to restore +x and one to execute the script.

**Comment by rhuss** [comment]
There is a known issue with Windows which looses the execution permission. For a complete discussion please refer to #477, but in short with 0.15.9 you have the following options:

* You use an assembly with an assembly descriptor which adds your `postExec` script. In this assembly descriptor you can add a file mode for the entries in a fileSet. Then you create the assembly with a `<mode>zip</mode>` (or tar, but not `<mode>dir</mode>` since you will loose the permission again).
* You add a `<permissions>exec</permissions>` to the assembly descriptor which will add the exec bit to every file. A somewhat ugly workaround but the way that Docker recommends.

Does this help ?

As a workaround you could also use 'sh /path/to/my/script' as command to explicitly call your script, too, so you dont have to rely on the execution bit.

**Comment by robzet** [comment]
@rhuss Thank you very much! That worked well. I can now run the script because the execute permissions are kept on windows as well after changing the assembly mode to 'tar' in the pom-file.

**Comment by burtsevyg** [comment]
My configuration
 ```
                                        <wait>
                                            <time>30000</time>
                                            <exec>
                                                <postStart>/opt/postStart.sh</postStart>
                                            </exec>
                                        </wait>
```
/opt/postStart.sh return 1 exit code.
Why postStart script did not fail maven build?
How can I do this.

**Comment by rhuss** [comment]
Currently the exit status of a `postStart` is not checked at all (would require an extra API call). That's probably not that difficult, but its simply not implemented yet.

If you think this would be a useful addition, then please open an extra issue for that, describing your use case. thanks !

**Pull request merged**
