### PR TITLE
read 'docker.follow' from System.properties only

### PR DESCRIPTION
**Pull request by jgangemi**
fixes issue #249

Signed-off-by: Jae Gangemi <jgangemi@gmail.com>

### CODE REVIEW

**Comment by Gengar003** [comment]
Why is removing a configuration point a good thing?

**Comment by jgangemi** [comment]
b/c it's not a valid configuration setting, see #249.

**Comment by rhuss** [comment]
Thanks !

I merged it, but could you please do me a favour and let's stick to the traditional way of PRs of sending them from your repo ? Probably accidentally you created the branch on this repo (not on your rebased fork).

This would help me in keeping the main repo more focussed.

**Comment by jgangemi** [comment]
that's weird - not sure how i would have manged to do that but i'll be sure to pay attention in the future.

**Comment by rhuss** [comment]
No problem, btw :)

**Pull request closed without merging**
