### PR TITLE
append $basedir to all output directory paths

### PR DESCRIPTION
**Pull request by jgangemi**
fix for issue #97

### CODE REVIEW

**Comment by kuhnroyal** [comment]
Noticed this as well today, I only fixed it for the source directory before.
LGTM

**Comment by jgangemi** [comment]
yeah - i actually just realized something else is potentially wrong w/ this - if you build two images, the data from one will override the data from the other in the output dir, so you loose the ability to see what was done for previous images.

i'm going to add an additional enhancement to this that will include the image name as part of the output directory path.

**Comment by jgangemi** [comment]
to prevent annoying merge conflicts this should be pulled after #105

**Comment by kuhnroyal** [comment]
Yea nice, ran into the problem you described last night. Lucky for me I have different folder names inside the 3 images so it is just added weight but not overridden.

**Comment by jgangemi** [comment]
this was closed w/o a merge - was that correct? re-opening for now...

**Comment by rhuss** [comment]
ah, yes. sorry.

**Pull request merged**
