### PR TITLE
Update dynamic host prop even without dynamic port prop

### LINKED ISSUE #323: Dynamic host property in port mapping is not filled in if port is specified
I have a port mapping config like the following:

```
<run>
    <ports>
        <port>+docker.ondemand.postgres.host:docker.ondemand.postgres.port:5432</port>
    </ports>
</run>
```

Ordinarily, I can access `${docker.ondemand.postgres.host}` & `${docker.ondemand.postgres.port}` after the docker container has started.

But if I specify `-Ddocker.ondemand.postgres.port=5432` then `docker.ondemand.postgres.host` is not dynamically set.

This appears to be because of the following snippet in `org.jolokia.docker.maven.service.RunService#createAndStartContainer`

        if (mappedPorts.containsDynamicPorts()) {
            updateMappedPorts(id, mappedPorts);
        }

Changing it to

        if (mappedPorts.containsDynamicPorts() || mappedPorts.containsDynamicHostIps()) {
            updateMappedPorts(id, mappedPorts);
        }

seems to fix this bug, so I'll raise a PR for this.

### PR DESCRIPTION
**Pull request by caspark**
Fixes #323 (see that for background).

### CODE REVIEW

**Comment by jgangemi** [comment]
cool - can you pls go back and sign this request? 

see here: https://github.com/rhuss/docker-maven-plugin/blob/master/doc/contributing.md

thanks!!

**Comment by caspark** [comment]
Woops, sure - will do on Monday.

> Also, your pull request should be rebased to the current branch integration. All this is nicely explained here.

Would you also like my PR rebased on top of `integration` - or is that not as important?

**Comment by jgangemi** [comment]
no worries - i forgot to do it sometimes myself.

if you could rebase, that would be great too!

**Comment by caspark** [comment]
Done as #331 .

**Pull request closed without merging**
